altering code deploy pipeline

diff --git a/.github/workflows/blue-green-deploy.yml b/.github/workflows/blue-green-deploy.yml
--- a/.github/workflows/blue-green-deploy.yml
+++ b/.github/workflows/blue-green-deploy.yml
@@ -13,49 +13,48 @@ permissions:
   contents: read	# Required for actions/checkout
 
 jobs:
-    app-deploy:
-        name: Deploy application
-        runs-on: ubuntu-latest
-        outputs:
-          image: ${{ steps.build-and-push.outputs.image }}
-        steps:
-            - name: Checkout code
-              uses: actions/checkout@v2
+    # app-deploy:
+    #     name: Deploy application
+    #     runs-on: ubuntu-latest
+    #     outputs:
+    #       image: ${{ steps.build-and-push.outputs.image }}
+    #     steps:
+    #         - name: Checkout code
+    #           uses: actions/checkout@v2
 
-            - name: Abort if Not Confirmed
-              if: ${{ github.event.inputs.confirmation != 'deploy' }}  # Runs for any input other than 'deploy'
-              run: |
-                echo "Workflow is aborted because you did not say 'deploy'."
-                exit 1 # Exit with a non-zero status to fail the job
+    #         - name: Abort if Not Confirmed
+    #           if: ${{ github.event.inputs.confirmation != 'deploy' }}  # Runs for any input other than 'deploy'
+    #           run: |
+    #             echo "Workflow is aborted because you did not say 'deploy'."
+    #             exit 1 # Exit with a non-zero status to fail the job
 
-            - name: configure aws credentials
-              uses: aws-actions/configure-aws-credentials@v2
-              with: 
-                  role-to-assume: ${{ secrets.ECR_ROLE_ARN }}
-                  aws-region: eu-west-2
+    #         - name: configure aws credentials
+    #           uses: aws-actions/configure-aws-credentials@v2
+    #           with: 
+    #               role-to-assume: ${{ secrets.ECR_ROLE_ARN }}
+    #               aws-region: eu-west-2
 
-            - name: log-in to AWS
-              id: login-pf-aws-ecr
-              uses: aws-actions/amazon-ecr-login@v1
+    #         - name: log-in to AWS
+    #           id: login-pf-aws-ecr
+    #           uses: aws-actions/amazon-ecr-login@v1
 
             
 
-            - name: build and push new image
-              id: build-and-push
-              #env: 
-               # ECR_REPOSITORY: 903497499610.dkr.ecr.eu-west-2.amazonaws.com/url-shortener
-                #IMAGE_TAG: latest
-              run: |
-                cd ./app
-                docker build -t 903497499610.dkr.ecr.eu-west-2.amazonaws.com/url-shortener:latest .
-                docker push 903497499610.dkr.ecr.eu-west-2.amazonaws.com/url-shortener:latest
-                echo "image=903497499610.dkr.ecr.eu-west-2.amazonaws.com/url-shortener:latest">> $GITHUB_OUTPUT
+    #         - name: build and push new image
+    #           id: build-and-push
+    #           #env: 
+    #             ECR_REPOSITORY: 903497499610.dkr.ecr.eu-west-2.amazonaws.com/url-shortener
+    #             IMAGE_TAG: latest
+    #           run: |
+    #             cd ./app
+    #             docker build -t 903497499610.dkr.ecr.eu-west-2.amazonaws.com/url-shortener:latest .
+    #             docker push 903497499610.dkr.ecr.eu-west-2.amazonaws.com/url-shortener:latest
+    #             echo "image=903497499610.dkr.ecr.eu-west-2.amazonaws.com/url-shortener:latest">> $GITHUB_OUTPUT
 
 
     blue-green-deploy:
         name: Blue Green Deploy
         runs-on: ubuntu-latest
-        needs: app-deploy
         steps:
             - name: Checkout code
               uses: actions/checkout@v2
@@ -82,7 +81,7 @@ jobs:
               with:
                 task-definition: task-definition.json
                 container-name: container_name
-                image: ${{ needs.app-deploy.outputs.image }}
+                image:  ${{ secrets.ECR_REPOSITORY }}:latest
 
             - name: Set appspec.json values
               id: set-appspec-values
@@ -93,7 +92,7 @@ jobs:
                 codedeploy-deployment-group: blue-green-deployment-group
                 container_name: app
               run: |
-                export TASK_DEF_ARN=$(aws ecs describe-task-definition --task-definition="$container_name" | jq '.taskDefinition.taskDefinitionArn')
+                export TASK_DEF_ARN=$(aws ecs describe-task-definition --task-definition="blue-green-task" | jq '.taskDefinition.taskDefinitionArn')
                 cat ./.github/workflows/appspec.json | jq --arg key "$TASK_DEF_ARN" '.Resources[].TargetService.Properties.TaskDefinition=$key'> .aws/appspec.json
                 sed -i 's#\\"##g' .aws/appspec.json
 
